[workspace]
members = [
    "qnum",
    "qnet",
    "qnetx",
    "qmesh",
    "qlink",
    "ci_core",
    "sim",
    "deploy",
]

# Exclude non-crate directories
exclude = [
    "docs/*",
    "examples/*",
    ".github/*",
]
